---
# tasks file for vm_azure
tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group_name }}"
      location: "{{ rg_location }}"
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group_name }}"
      name: "{{ virtual_network_name }}"
      address_prefixes: "{{ vnet_address_prefixes }}"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group_name }}"
      name: "{{ subnet_name }}"
      address_prefix: "{{ subnet_address_prefix }}"
      virtual_network: "{{ virtual_network_name }}"
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group_name }}"
      allocation_method: "{{ publicip_allocation_method }}"
      name: "{{ publicip_name }}"
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group_name }}"
      name: "{{ security_group_name }}"
      rules:
        - name: "{{ security_group_rule_name }}"
          protocol: "{{ security_group_rule_protocol }}"
          destination_port_range: "{{ security_group_rule_destination_port_range }}"
          access: "{{ security_group_rule_access }}"
          priority: "{{ security_group_rule_priority }}"
          direction: "{{ security_group_rule_direction }}"
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{ resource_group_name }}"
      name: "{{ netowrk_interface_card_name }}"
      virtual_network: "{{ virtual_network_name }}"
      subnet: "{{ subnet_name }}"
      public_ip_name: "{{ publicip_name }}"
      security_group: "{{ security_group_name }}"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group_name }}"
      name: "{{ vm_name }}"
      vm_size: "{{ vm_size }}"
      admin_username: "{{ vm_admin_username }}"
      admin_password: "{{ vm_admin_password }}"
      ssh_password_enabled: "{{ vm_ssh_password_enabled }}"
      network_interfaces: "{{ netowrk_interface_card_name }}"
      image:
        offer: "{{ vm_offer }}"
        publisher: "{{ vm_publisher }}"
        sku: "{{ vm_sku }}"
        version: "{{ vm_version }}"